### ISSUE TITLE
Fix: remove possible warning

### ISSUE THREAD

**Issue by Mr-Maslo** [infoweb-internet-solutions/yii2-cms-menu#23]
In class MenuItemController in method findActiveMenu if no valid active menu-id is set call Menu::findone() is incorrect and causes the warning: **"PHPWarning: Missing argument 1 for yii\db\BaseActiveRecord::findOne(), called in .../MenuItemController.php on line 496 and defined"** because method ActiveRecord::findone has 1 required argument.

Correct call is: Menu::find()->one()

**Comment by infoweb-internet-solutions** [comment]
thanks
